### ISSUE TITLE
SMF 1 support

### ISSUE THREAD

**Issue by Underdog-01** [SimplePortal/SimplePortal#14]
This is not really an "issue" but rather an old idea.

How about dropping SMF 1 support?
Not too many people are using it anymore especially since hosts are dropping older PHP versions.

**Comment by silentguardian** [comment]
I had planned to drop the SMF 1.1 support with 2.4 version when I first started working on it.

The new plan is to release 2.3.8 as is and swap SMF 1.1 support with SMF 2.1 with the next version.
